framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: ~
    session:
        name: sensiotv-session
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
